language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: fh31fLdJX1XAmdesjXYxYPSApTJnEeIU+X9EDrPxMX956tBamWRxsNnn05mxDjenQVNaTmwDKZC/qXzYmZgCZ5aLCcKNNnoEIs7tGUmioP8tp7pBNBrw8oJQSdh/r2jBcn0zzyAAi4ZO+dCfN3KEP/6rowvMEnGnxcDf++EgaH/YzQApFtCyQ+SUDeegn2ontxdvSsS5x6DFIGF329NrxTPlQjl0yd6Zb8rr5kJJK5QN4pF1fhooxzw+X929kt1icvi+11pVQhxHeCSKhevu5M4y/lfoRTQPs/W7KsqTuT2pnNl3OhfVywubqU82GeD6UX0NnenMCRJzIHBtXn9ueLxyELVLJqTbD5b80TbWXkcwqz7N00ySYA/B5BeTspwzHG+8FW0dVEvL7MziOK5TtKvowPqkW5Z8dI9WMSMz6e+fPxcMJx3/V5BpgKeiKBD+qshyUNVtd2/rqtQIbZmPLLFzagh2mfqzZOCfQVy1BpmtqABcczLwl2auIhURJ69RjekP3z8qikVDgQAGiT8d6n0iqJ6xSBqAWn1VEWzAjOj6052x0KUVJxTb3aeR8+mM8Wx/kZ/hPvkgVHMvfnWGvhGepvZPzCMbtCKf7TFPeET6a2nKd/HwS8TW4+rg8BmbiTTX6SjNUP/bxH6by1csQ2Dtf93yMlQQBtdvxRmcWJ8=
  app: super-reservation-bot
