language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: R46SQgIbhmo1Mknz/M9rtSt7JI0PlRxSGxylUQF/iyDO3Xs2CluuQN/gtLqvUIhglKCTYyl4esbWY9R35zNS90v3I+FbbOUv5LnvbmDk1yq0EGM30BXb0WVX7d9nUlUbtmyRDn47p+UdFaAINN7VGV51rUgm+aZLjdnpxEdEzjzxEhG8wBGXczZ1nknIOv6bRL8seAMXOQH/qvjh3wjEBQnl2vBBvKzqVqvoH7OgVTNJY8ipaoQnDQ4AMb5ki960adgYkCVdOdnM7J1DFHNlgqcyFpwenlke8xPtk9FBD3LDQ/95vh6J66wW0/D66j6LsXxHJNYLWIj9cqjfKnHCFV/kTX1n4eU9PNKLVwl+tvzyIiedVfyPZA1j9wrayHNn020CPfeNvVGsfuaaFgqsI2JzYVRA2kloapGKvTQ7vRDdt8Yknvx7obIxiZkpGmE9VNLmhL5TAx/RBdfoaieQTdXL6F+Gtb/3szzw+szu2g8FavGpRdrEJhDLr5qnPHrHDCLhAQmPh6RggjAEVN5aWPmJtSf1UGUjrA/ZuAggytqvloq6Un9Xc8k01Z0Cqmlo95AhUtxh7xa32LUFMYLe1A0gojeKJcJoGI/sqSJuLWtASw9AML+6Kifyg0c+2773hUltI7OQ5cDs4owRx6Wpfc34FNKpIfCKvNTduUvkS20=
  app: super-reservation-bot
