language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: KzcQKaTyktp76d4QWVk4Va4TJGCntPXwIUl1gtHL91goM/rMdFckLJRK1ZTaCrCtmJwCqvM625ds5EH7SbTdxM5HW1r7IZM1P3o2kYMW3B0D4+IbluSFFi+EyT9MNpRzIz+iwpYqPBRKR9vILO4ye4LNW203v5s9mxbn1ctLb6n/oT/xabLO+WbFdhHtnIX5lebdZ7vHszHFx3/FEnL1ocu+fSnm43P1Dqd2a8eQZrBMB4/SaCu76+uWKtZEMZ4xkQimaDsS/SaJ+MRnf6fK0J9OFJCs1MDn0ctttfcgujnxrwe+3SQI4dHxuAI24VBFDKJzdtqV/+x6iBcDaoSWpAwrAzs3to+T3p1m2gDwwDTX0MMYxnqBuHcqefaIDMxkH8YFOMBathuH6/x4QCM4qHR9p1F0gOtlwdNyedEFXxHdNdRyhCWR7mRpGzbco5N+V1LxlEAKpY5/VX1St+sZVaSwDQodP5OkOV7oQfiyXqL86CBVPQg0nGkNQqcWUp5R/0JGfzGAHPhFq6Twkko6uQIqx8uJ5JNH8RNw9r8t03+AuJ5cxJRB/AcCnXhS8VByvs8LRnwYfEeTw8M7vnWo6x4dy9oJbniT3B4gSzZN5YAmBCdrKPVjcx1gC7jpIWEkL8s0aMZoM8RJznkri5z7Db5Zo2q5Y9Dkr3CmCmtddTk=
  app: super-reservation-bot
