language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: r6PUd8L6nLfAj4+rh1qWCMuL70R1GoBuul2PLKZ0yudixdl22xmPIg+rH3bh43Zd67Q0xln0KDmR2jSpX/yRB+eiYoF0CKWhVDS9uMG9vQGgvU31HVOsXwpDnddwH6Wpu8IQ1wTRC6jxB8bCu0Q+uDQl5Zsmz5LjXqK5rnn/N+qWJRGpOmx2E3bSKSStKjMPlAN3YUK9uczcDjI/Dux8HHG3uu/thrJ9daIdLuGEbJkZVEIcJEPG5b4sjRA19ko/d2WQNRrxvF6a4ByJJQBwFMFHKvSPYHSw9uUws94BPStCogWn46B1TPOduN9mwFEDdx2YyIZ3gwdOmp02OFFiU9WbatnkysC6QacSVdY5MI4GlvFVJyNkDtDAgKWahIn4XtnkeJ1IyuV++5Jso42Tm4HNVs+MrNNFQMD3JBekBFuR2konyM70zAr+tgrmOCYx/M63pcFOZ5gJhjQ/H6hqMkBm1wU4q0/1V/Y0Xsjok48LPsHc/OYeYT8rwJTOT6ph/YxKHftBEhyaxXtJaZpALbS4NvsQ4gHh4L52RJ+7zCmfsGaHzKGlC/gLZByx/f3UUW1IQIfErpit5Y6UktUSPMSdxou+diH5dfGeoFpoPz5+gTj5l/4wgqe88G77M5nnl/x8SS3kSAveu69MjSgBTO0G1w9qajYB6mo61PoDOiE=
  app: super-reservation-bot
