language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: EDZhb9kEzs9LbK1EN95l8fTABooTUItqwcHmTHAZFoU/8iH6gKqnkvZzSBDhGQJgrn2RGUfBTIIXYseSOI7dirEsjGHnc1lFC9R9X5szR7iEyKwGoPb6L6sWJqoAXFh8tYpUWIkrsBh4dD0iijfCmUzBoLyaCS7BArt2SDhpznKRTNaTr1eP8WxgkMGmTnGeDeK0eTpqamf5VcWu56lDVA57cZAqluD2gcbRwyRYzvgYs9FlqqBQ4Mje4VyIZ0U1p5Bh6Rz7HuJSoa2njISbZam/PojH9wFEH+KO2aDa0VLIV+AcAQXMMM/hNmJwhGXvN0x7vH3fEQ8fE9vC2qTOWRqN9U7BiP7925bcaWEygQjGHaqOHNJ9KM7DyXgDQ85a+7od6I5z6FkormqlvXn2bs1l6rbbCOLjIGnaJjf4UJ86s0LUhlRNL+uwGKI+07fBDIGTI5k1NsrRrUcsNp+Vyq6s7t8NzhRUv9vr1xUjV+mrygnyPzwh1Z5SoNg5ju4Dd0ZO1rlcUYsRQg94OZ3dA/SEECtZwW+e1TTSxj6ZVC8AnzMAkTK3OyGjlO2gmTu/zs0IOfY3p6dtdfM3IT1dLS6epLSfHS6J00LaUynX4GxovyMaUIEuF4LIvft9P+IIUNLBtiuwUCmobaj2hvO9KgBlIfgSH95CUtC1PcdE8l4=
  app: super-reservation-bot
